language: go
go:
- '1.10'

before_install:                                                                 
- curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh  
- dep ensure

script:
- go build
- mv terraform-provider-xenserver terraform-provider-xenserver_$TRAVIS_TAG

deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file: terraform-provider-xenserver_$TRAVIS_TAG
  skip_cleanup: true
  on:
    tags: true
